export const data = [
  {
    location: "IHENE",
    date: "05/09/2021",
    type: "Sangue",
    direction: "Espontâneo",
    id: 1,
  },
  {
    location: "HEMOPE",
    date: "05/09/2021",
    type: "Plaquetas",
    direction: "Reposição",
    id: 2,
  },
  {
    location: "IHENE",
    date: "05/09/2021",
    type: "Hemácias",
    direction: "Espontâneo",
    id: 3,
  },
  {
    location: "IHENE",
    date: "05/09/2021",
    type: "Plaquetas",
    direction: "Reposição",
    id: 4,
  },
  {
    location: "IHENE",
    date: "05/09/2021",
    type: "Sangue",
    direction: "Espontâneo",
    id: 5,
  },
  {
    location: "IHENE",
    date: "05/09/2021",
    type: "Hemácias",
    direction: "Reposição",
    id: 6,
  },
  {
    location: "IHENE",
    date: "05/09/2021",
    type: "Sangue",
    direction: "Espontâneo",
    id: 7,
  },
  {
    location: "IHENE",
    date: "05/09/2021",
    type: "Sangue",
    direction: "Espontâneo",
    id: 8,
  },
  {
    location: "IHENE",
    date: "05/09/2021",
    type: "Sangue",
    direction: "Espontâneo",
    id: 9,
  },
  {
    location: "IHENE",
    date: "05/09/2021",
    type: "Sangue",
    direction: "Espontâneo",
    id: 10,
  },
  {
    location: "IHENE",
    date: "05/09/2021",
    type: "Sangue",
    direction: "Espontâneo",
    id: 11,
  },
  {
    location: "IHENE",
    date: "05/09/2021",
    type: "Sangue",
    direction: "Espontâneo",
    id: 12,
  },
  {
    location: "IHENE",
    date: "05/09/2021",
    type: "Sangue",
    direction: "Espontâneo",
    id: 13,
  },
];
